### ISSUE TITLE
Implement Collection CRUD operations

### ISSUE THREAD

**Issue by ssone95** [ssone95/ChromaDB.Client#3]
Implement support for other collection-related operations.

**Comment by cincuranet** [comment]
I think, with all my latest changes, all collection operations are complete. So maybe this could be closed.

**Comment by ssone95** [comment]
> I think, with all my latest changes, all collection operations are complete. So maybe this could be closed.

Yes, I was planning to resolve it, just wanted to check with you whether we're all set with that
