### ISSUE TITLE
Should ChromaDB.Client.Extensions be separate?

### ISSUE THREAD

**Issue by cincuranet** [ssone95/ChromaDB.Client#54]
I'm wondering whether `ChromaDB.Client.Extensions` should be separate. My reasoning is that most people will find and install _ChromaDB.Client_ package and hence it would make sense to include it there. It will also result in having less packages and hence less versions for people to align. Finally now the extensions are in `ChromaDB.Client.Extensions` namespace, which makes it even less discoverable, so I would propose to put it into `ChromaDB.Client` namespace.

What do you think @ssone95?

**Comment by ssone95** [comment]
Hi there,

Somehow I missed this email thread, but yes, to me - it’s definitely okay
to keep them separate, so we can proceed with *.DependencyInjection name.
